global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'server-node-1'
    static_configs:
        - targets: [ '95.163.214.47:9100' ]

  - job_name: 'server-node-2'
    static_configs:
        - targets: [ '89.208.197.225:9100' ]        

  - job_name: 'server-node-3'
    static_configs:
        - targets: [ '5.188.140.11:9100' ] 
