global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'server-node-1'
    metrics_path: /metrics
    static_configs:
        - targets: [ '95.163.214.47:9100' ]

  - job_name: 'server-node-2'
    metrics_path: /metrics
    static_configs:
        - targets: [ '89.208.197.225:9100' ]        

  - job_name: 'server-node-3'
    metrics_path: /metrics
    static_configs:
        - targets: [ '5.188.140.11:9100' ] 

  - job_name: 'api-server-1'
    metrics_path: /metrics
    static_configs:
        - targets: [ '95.163.214.47:5000' ]     

  - job_name: 'api-server-2'
    metrics_path: /metrics
    static_configs:
        - targets: [ '89.208.197.225:5000' ]                     

  - job_name: 'api-server-3'
    metrics_path: /metrics
    static_configs:
        - targets: [ '5.188.140.11:5000' ]      

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
        - targets: [ 'nginx-prometheus-exoprter:9113' ]   
