version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  nginx-prometheus-exoprter:
    container_name: nginx-prometheus-exoprter
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
