version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - nginx-net

  nginx-prometheus-exoprter:
    container_name: nginx-prometheus-exporter
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://nginx:8080/stub_status
      - http://nginx:8080/stub_status
    ports:
      - "9113:9113"
    restart: always
    depends_on:
      - "nginx"
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
